# Generated by Django 4.0.3 on 2022-03-27 16:15

from django.db import migrations
import scheduler_apis.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', scheduler_apis.models.UserManager()),
            ],
        ),
    ]
